version: 2.1
jobs:
  build_docker:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build -t takeoff-base:latest -f Dockerfile .

  build_and_push_docker:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build -t takeoff-base:latest -f Dockerfile .
      - run:
          command: |
            TAG=$(if [ -z "$CIRCLE_TAG" ]; then echo "SNAPSHOT"; else echo $CIRCLE_TAG; fi)
            echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
            docker tag takeoff:latest schipholhub/takeoff-base:${TAG}
            docker push schipholhub/takeoff-base:${TAG}

workflows:
  version: 2.1
  deploy:
    jobs:
      - build_docker:
          filters:
            branches:
              ignore: master
      - build_and_push_docker:
          filters:
            branches:
              only: master
            tags:
              only: ^[0-9]+\.[0-9]+\.[0-9]+$
